In [102]:
print("In the name of Allah")

In the name of Allah


In [103]:
# Creating numpy/n-d arrays

import numpy as np

arr1 = np.array([1,2,3,4,5])
arr1


array([1, 2, 3, 4, 5])

In [104]:
type(arr1)

numpy.ndarray

In [105]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
arr3 = np.zeros((2, 3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [107]:
arr4 = np.ones((3, 3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [108]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [109]:
arr6 = np.arange(10)
arr6

arr6 = np.arange(5, 16)
arr6

arr6 = np.arange(5, 16, 2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [110]:
arr7 = np.linspace(10, 20, 10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [111]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [112]:
arr1

array([1, 2, 3, 4, 5])

In [113]:
arr1.shape

(5,)

In [114]:
arr2.shape

(2, 3)

In [115]:
arr9 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [116]:
arr9.shape

(2, 2, 2)

In [117]:
arr9.ndim

3

In [118]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
arr2.ndim

2

In [120]:
arr1

array([1, 2, 3, 4, 5])

In [121]:
arr1.ndim

1

In [122]:
arr1.size

5

In [123]:
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [124]:
arr9.size

8

In [125]:
arr9.itemsize

8

arr9 = np.array([[[1, 2], [3, 4]], 
                 [[5, 6], [7, 8]]], dtype=np.int32)
arr9.itemsize will print 4 then

In [126]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [127]:
arr8.itemsize

8

In [128]:
arr8.dtype

dtype('float64')

In [129]:
arr9.dtype

dtype('int64')

In [133]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [138]:
lista = range(0, 100)
arr11 = np.arange(100)


In [139]:
import sys
print(sys.getsizeof(87) * len(lista))

2800


In [143]:
print(arr11.itemsize * arr11.size)

800


In [144]:
import time

In [169]:
x = range(10000000)
y = range(10000000, 20000000)

start_time = time.time()

c = [(x, y) for x, y in zip(x, y)]

print(time.time() - start_time)

2.1057803630828857


In [170]:
a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start_time = time.time()
c = a + b

print(time.time() - start_time)

0.47740888595581055
